{% set version = "5.0.225" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-chemospec
  version: {{ version|replace("-", "_") }}

source:
  fn: ChemoSpec_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/ChemoSpec_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/ChemoSpec/ChemoSpec_{{ version }}.tar.gz
  sha256: 21786e12fb04ff2a258056e77a133ec159fa63f639913932b09e01d1219dc7d7

build:
  noarch: generic
  merge_build_host: True  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
  host:
    - r-base
    - r-chemospecutils
    - r-plyr
  run:
    - r-base
    - r-chemospecutils
    - r-plyr

test:
  commands:
    - $R -e "library('ChemoSpec')"           # [not win]
    - "\"%R%\" -e \"library('ChemoSpec')\""  # [win]

about:
  home: https://github.com/bryanhanson/ChemoSpec
  license: GPL-3
  summary: A collection of functions for top-down exploratory data analysis of spectral data
    including nuclear magnetic resonance (NMR), infrared (IR), Raman, X-ray fluorescence
    (XRF) and other similar types of spectroscopy. Includes functions for plotting and
    inspecting spectra, peak alignment, hierarchical cluster analysis (HCA), principal
    components analysis (PCA) and model-based clustering. Robust methods appropriate
    for this type of high-dimensional data are available. ChemoSpec is designed for
    structured experiments, such as metabolomics investigations, where the samples fall
    into treatment and control groups. Graphical output is formatted consistently for
    publication quality plots. ChemoSpec is intended to be very user friendly and to
    help you get usable results quickly. A vignette covering typical operations is available.
  license_family: GPL3
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'

extra:
  recipe-maintainers:
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
    - cbrueffer
    - dbast
