appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: eZN/QaIN7q9/h14Qmi4kDPWv9vc5gkKeSY/YcorHrfSKrAraFbloxckwAf/le2EV9HGvDp03K3zrpboXGejMKDVHxWIu2DOkgE2tm/sA4aO2zyOe/opnJkZlVKyQj7EplKPCHfGPhgeWvtbAn1e4DyX/8QlEO4qHFEy6fU3/pE7/RO/VUb5DR4dlSCaoS5IrKTZAW2zU2nBAg5/8O56CMGSpICzKkceDNi0q8iuJv4V9aFeCz6xWyZEWWUkE02PpwMV4Rn2obQebAa5fRl4WohxQGrJlIg9w9cDZ04UbBr9s7sh2NQnQRv4PF6Rq9DIBgiaB6Ku/8LVBlRKPU7ITpgfrc48gJ1IIF9KiPir4n18b1JZJWLPNJDx+7nerYM4DpQCE+GLNobf7EiI7mS4QlWtUNuXRA+PxcG//CBO20h0jh8sejxkNnp6lKVr+jcjCDGVA5vbU0M8u22KwNQoG9s+XXUw0IKdmGX7SYg+RY2qAU/385GJUQoJEfO9neztP/DLHhZ+XVxUHdZzUXy67B6mRsTajcOg1v2EWDuuhTRLtqd8goA9hXNFpYvtHbPYabhR7wwJ9p28vh+IilXBpoypPtWW9Ndo8Y9Q2OCxcr/aU6WMKa0bqERM7EaMcLmhkpP6uzG8R/A6npoY63ybI/W5ByjYBjJe76qw9fLpFP5o=}
