travis:
  secure:
    BINSTAR_TOKEN: f3n9BNOqSSjamtA555p+0x5Y4mHdZHH6SPC68Fm7SltLJpDVyeQCVLbzgg3Pp0KfPePjKiGYI7HyCzCPaXzLgYIumwmAflC/ABqw6vQ4foMowaJ/teyILtKPzJOsgPd40QJDXsjc7aKdbpPGoeX0JvTGfRK5QWlMP3B69/Z4PvC4CoQ0brSkWH15EV73bveuaFOej6cZCkhJ3C+oobr19d/TgdAjk8gYBXBvqO8AdePV3oqlox1X+nhk908UUHWX/mL0wLqUncjNcn4P8hympeW5m2MiJNqsfikVx2aK6XOEYq9L/sG6Orgl5pVHtrJnJOvCmSX8GCXtFlzPpiP7B7F4ChBmiV+/YGu6AeAZihE08o6DUGLwHuMJgKKrq06q8MbJGOqEZ3poz5pnC0wNU+7rJQdhI8E+/WP7qfDgMbBbDmmxMqJBukqTQ+4fodS2GKBHRemmIjlm0wyx3Dd3Dyh7h8HQpuZBWxvUNRlc92cre+HgfxXvcv5c3u9V3oohZJAMTeb1C4/V4bIojOSLEvP2ubvjFVwvKMx8pPk0+p4yfSLU1BlLVtsymd4+yB9BiUX4bvwb9DN9H9jtWGJj6tLT1t2P9t4zk5m/JlxssT9Ujn1BGPu+4QvhZHiX14WW2OhvnRl/ps+pVVbEIV2B+FEEsylXkVMa9u1VKTXFPNU=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
