travis:
  secure:
    BINSTAR_TOKEN: VB9Is5Y4DjF3MmLw13jSm+x3G8vWoCUJ+YEexRYpq8DzIbTNktFzwugTd7sMiX+8jbbgrQ4n33iMdCdtOoIHRXQtfjaFWvCwIG93Fr4iYibwGu6AnD6jiCqNpewBSI0yefOjUwp+wPNuM8E42vM5fs5knqxJMOtVk59Sy7iSDK2NBhB7nTYGPoPr6uf1P5JTLmnJsviLFdQ5B80QxBTKuJP016xSxe26/tZj0TuuuvxD3TLzJs7q9AHJUP27VCP+ozGfbP7loskGtOnBs/L/hT/c5Oo5k/zAGBueGdgPqN8YseQXbhTj7FE++wpIsqJZqtcqwBtHKyN6gIAV3YOOnCWO28nj9feED6hZmF5Y9/q16A+fJnPqXGQQEFWdwWGf3k1rmxZdbjKxDLtVsTA0zFQ1+20MTCdPORPmN00tyQZEbxqC3BIq0bvJa0PQDzJt/k4ariQ/oK6aTThpf5IPZtxeRjJ3UYOrUwh6OqNzFCorepaH9iogj0UBlqMhl7lAEeEFCQ6I9mUuy4BrJdo3P83ZSLJvs7LB179TGLCVezoM7+spAVIuJgNnFwNhCiqHEPfPjvg+IGjM1/1s8QDIZkSIrHOnssCrgDLjvCRHE/kx7KzVacYVx0q5YS+04wlZbaW0gUme+bVGlNRJiiXN/x2Iq27agfn1Uxky8AcHqhQ=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
