travis:
  secure:
    BINSTAR_TOKEN: 1KMS7ES5d736WTXVfKbzeOHD7NO7WkPY16ajLvCOTZ6NQuiejOmvUxXorQXUBAcQh8DrToUqTOut0glmlI/fQqvTorig5n6zBQXQ2d6ZuWLfQVGCJKDEq8b2KOoUwZPK7lbdS1olEWOVDE93hoOlsDyrZREvlL2POtsez+Jelh1gN6qQwT4h9HNoe+D/PDiuP76E85UqNzjBZJJSTPThdzkm3GKX8jHXM90Kvuv99lvZnscjjlnQa/Q89ijpb+SUGsXOMJRKuCb8huha9Rh9Mn11Qjr5sjdtbTcWVEJFKH4XJqfYXNwK2uXxpLji8SHWfQDP9do8wuZhq9jxGFuhGDAP/BhaCKR5FB6EHTz6zYgttFcFGH9RcJ6NQ2+zAOFnV5DIau+UE9gjogLbwge7k4TvegX7XcHLpJjyJle4VztfADLd5QDuDBfPzropuI4QF5WwLa6VNNqSj5x0v8KTd0zicUW0U9orVSo4RbGTFMXly3cddLmLUg13DkeTiC8nUKjav/HxGiIM3M4uS6BrXuS/zGOKKpZxlY1H9y+P0kNHut3gYZ9uyeCiYxKs6qkjo+ImBi/LBswlpk+OeP0NVEcsUGTInDW/+F8tmTbPqkCndEpRZdrCz5bicxgI12ll91W4F/GuUi3QjfGC3KrBKDQbrFbZFKI39d1DR0JG7uI=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
